version: "3.9"
   
services:
  db:
    image: postgres
    # volumes:
    #   - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoopass
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    expose:
      - "5432"  


  web:
    build: .
      # context: .
      # dockerfile: Dockerfile
    image: odoo_server_web
    command: python /opt/odoo/odoo-10.0/odoo-bin -c /etc/odoo/odoo-server.conf
    volumes:
      - type: bind
        source: .
        target: /opt/app
    ports:
      - "80:8069"
    depends_on:
      - db